"use client"

import { BadgeCheck, BrainCircuit, FileText, Github } from "lucide-react"
import { evidenceProjects } from "@/components/skillproof/data"
import { PageShell } from "@/components/skillproof/page-shell"
import { SkillBars } from "@/components/skillproof/skill-visuals"
import { useSkillProof } from "@/components/skillproof/skillproof-state"
import { ActionButton, MetricTile, NeoPanel, SectionTitle, StatusPill } from "@/components/skillproof/ui-kit"

export function ReportPage() {
  const { trustScore, state, runAnalysis } = useSkillProof()
  const projects = state.analysisResult?.projects ?? evidenceProjects

  return (
    <PageShell>
      <section className="container mx-auto px-4 py-12 md:py-16">
        <div className="mx-auto max-w-7xl space-y-8">
          <div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end">
            <SectionTitle
              title="Skill Report is generated by the"
              highlight="Scoring Agent"
              description="Scores combine project complexity, repository evidence, resume claims, certificates, interview answers, and Terminal3 identity status."
            />
            <ActionButton onClick={runAnalysis} variant="accent">Refresh report</ActionButton>
          </div>

          <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
            <MetricTile icon={Github} label="GitHub" value={state.githubHandle || "Open"} detail="Repositories, languages, commits, and complexity evidence." accent="bg-[#2F81F7]" />
            <MetricTile icon={FileText} label="Resume" value={state.resumeName ? "Parsed" : "Needed"} detail={state.resumeName || "Upload a resume to increase confidence."} accent="bg-[#FFC224]" />
            <MetricTile icon={BrainCircuit} label="Interview" value={state.interviewComplete ? "Scored" : "Pending"} detail="Rubric-based answers reduce claim-only scoring." accent="bg-[#15B8A6]" />
            <MetricTile icon={BadgeCheck} label="Trust" value={`${trustScore}%`} detail="Overall recruiter confidence score." accent="bg-[#FF6B7A]" />
          </div>

          <div className="grid gap-8 xl:grid-cols-[0.95fr_1.05fr]">
            <SkillBars />
            <NeoPanel className="p-6 md:p-8">
              <StatusPill tone={state.analysisResult ? "green" : "yellow"}>
                {state.analysisResult ? `${state.analysisResult.provider} analysis` : "Evidence breakdown"}
              </StatusPill>
              <h2 className="mt-4 text-2xl font-bold">Project complexity signals</h2>
              {state.analysisResult?.summary ? (
                <p className="mt-3 text-[15px] font-medium leading-6 text-[#393939]">{state.analysisResult.summary}</p>
              ) : null}
              <div className="mt-6 space-y-4">
                {projects.map((project) => (
                  <div key={project.title} className="rounded-2xl border-[3px] border-black bg-[#F7F7F7] p-5">
                    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                      <div>
                        <h3 className="text-xl font-bold">{project.title}</h3>
                        <p className="mt-1 text-sm font-bold text-[#5B5B5B]">{project.stack}</p>
                      </div>
                      <span className="w-fit rounded-xl border-[3px] border-black bg-[#FFC224] px-4 py-2 font-mono text-lg font-bold">
                        {project.score}%
                      </span>
                    </div>
                    <p className="mt-3 text-[15px] font-medium leading-6 text-[#393939]">{project.summary}</p>
                  </div>
                ))}
              </div>
              {state.analysisResult?.recommendations.length ? (
                <div className="mt-6 rounded-2xl border-[3px] border-black bg-[#FFF1BE] p-5">
                  <p className="font-bold">Next scoring improvements</p>
                  <div className="mt-3 space-y-2">
                    {state.analysisResult.recommendations.map((recommendation) => (
                      <p key={recommendation} className="text-sm font-semibold leading-6 text-[#393939]">
                        {recommendation}
                      </p>
                    ))}
                  </div>
                </div>
              ) : null}
            </NeoPanel>
          </div>
        </div>
      </section>
    </PageShell>
  )
}
